# Generated by Django 5.2.1 on 2025-05-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmessage',
            name='recepient',
        ),
        migrations.AddField(
            model_name='message',
            name='daytime_for_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки'),
        ),
        migrations.AddField(
            model_name='message',
            name='recepient',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Получатель'),
        ),
    ]
