# Generated by Django 5.2.1 on 2025-05-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notify', '0002_remove_logmessage_recepient_message_daytime_for_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='daytime_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время попытки отправки'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_notify.message', verbose_name='Текст сообщения'),
        ),
    ]
